changed github action and fixed bug in loops

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,21 +1,18 @@
-on: [push]
+steps:
+- uses: actions/checkout@v4
 
-jobs:
-  deploy:
-    runs-on: self-hosted
-    steps:
-    - uses: actions/checkout@v4
-    
-    - name: Build project
-      run: |
-        cargo clean
-        cargo +nightly build --release
-    
-    - name: Deploy/Run
-      run: |
-        cp target/release/NeoRust /home/volt/neo-rust/
-        chown volt:volt /home/volt/neo-rust/NeoRust
-        systemctl --user restart neorust.service
-        sleep 3
-        systemctl --user is-active neorust.service && echo "✅ Service running" || echo "❌ Service failed"
+- name: Cache Rust build
+  uses: Swatinem/rust-cache@v2
 
+- name: Build project
+  run: |
+    cargo clean
+    cargo +nightly build --release
+    
+- name: Deploy/Run
+  run: |
+    cp target/release/NeoRust /home/volt/neo-rust/
+    chown volt:volt /home/volt/neo-rust/NeoRust
+    systemctl --user restart neorust.service
+    sleep 3
+    systemctl --user is-active neorust.service && echo "✅ Service running" || echo "❌ Service failed"
